In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
!nvidia-smi  ###cuda version

Thu Mar 27 01:10:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
###to check gpu
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

Tesla T4
cuda


In [5]:
torch.empty(2,3)####matrix of 2 rows and 3 columns This empty is filling the matrix with any values. picking garbage value from memory.Its an empty array which can be filled later

tensor([[-1.1119e-07,  4.5521e-41, -1.1051e-07],
        [ 4.5521e-41, -1.1119e-07,  4.5521e-41]])

In [6]:
a=torch.empty(2,3)

In [7]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
type(a) ####pytorch works on tensor

torch.Tensor

In [9]:
a.fill_(0) #### thus we filled the tensor with zeo

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros(2,3) #### to check the zero matrix

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
###for one matrix
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(3,4) #####random

tensor([[0.9661, 0.1773, 0.0027, 0.7614],
        [0.4233, 0.3990, 0.0159, 0.0387],
        [0.7574, 0.0729, 0.9387, 0.8360]])

In [13]:
torch.rand(3,4) #### every time it will give different values

tensor([[0.7285, 0.5009, 0.6814, 0.0692],
        [0.6663, 0.9502, 0.2643, 0.5152],
        [0.4291, 0.8361, 0.2937, 0.7816]])

In [14]:
torch.manual_seed(10) ######to get same value
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [16]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [17]:
torch.tensor([[1,2,3],[3,4,5]]) ### creating custom tensor

tensor([[1, 2, 3],
        [3, 4, 5]])

In [18]:
torch.arange(10) ##### numbers0-9

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.arange(3,9) ####always excluding last number

tensor([3, 4, 5, 6, 7, 8])

In [21]:
torch.arange(1,10,2) ####jump of 2 - this is the range

tensor([1, 3, 5, 7, 9])

In [22]:
torch.linspace(0,10,20) ####generate 20 numbers between 0 to10 -we are giving ranhge and it will generate numbers between the range -used for creating random bits

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [23]:
torch.eye(5) ###identical

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
torch.full((3,3),5) #### 3 by 3 matrix filled with 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [25]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[7309469113269755962, 7310874250630362211, 7311068566657332339],
        [2322206415573840754, 2459013921893135650, 2459029315949715812]])

In [28]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

| Data Type                | Dtype            | Description                                                                                      |
|--------------------------|------------------|--------------------------------------------------------------------------------------------------|
| 32-bit Floating Point    | `torch.float32`  | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage. |
| 64-bit Floating Point    | `torch.float64`  | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory. |
| 16-bit Floating Point    | `torch.float16`  | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs. |
| BFloat16                 | `torch.bfloat16` | Brain floating-point format with reduced precision compared to float16. Used in mixed-precision training, especially on TPUs. |
| 8-bit Floating Point     | `torch.float8`   | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common). |
| 8-bit Integer            | `torch.int8`     | 8-bit signed integer. Used for quantized models to save memory and computation in inference. |
| 16-bit Integer           | `torch.int16`    | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision. |
| 32-bit Integer           | `torch.int32`    | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks. |
| 64-bit Integer           | `torch.int64`    | Long integer type. Often used for large indexing arrays or for tasks involving large numbers. |
| 8-bit Unsigned Integer   | `torch.uint8`    | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255). |
| Boolean                  | `torch.bool`     | Boolean type, stores True or False values. Often used for masks in logical operations. |
| Complex 64               | `torch.complex64`| Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks. |
| Complex 128              | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory. |
| Quantized Integer        | `torch.qint8`    | Quantized signed 8-bit integer. Used in quantized models for efficient inference. |
| Quantized Unsigned Int   | `torch.quint8`   | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks. |


In [32]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [33]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [34]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [35]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [36]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [37]:
c=torch.tensor([1,-2,3,-4])

In [38]:
torch.abs(c) #####absolute value(all positive that means all negative converted into positive)

tensor([1, 2, 3, 4])

In [39]:
torch.neg(c) ####negative

tensor([-1,  2, -3,  4])

In [40]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [41]:
torch.round(d) ####round off

tensor([2., 2., 4., 4.])

In [42]:
torch.floor(d) ####round down before decimal

tensor([1., 2., 3., 4.])

In [43]:
torch.ceil(d) ####round up above value of decimal

tensor([2., 3., 4., 5.])

In [45]:
torch.randint(size=(3,4),low=0,high=10) ####random integer

tensor([[8, 1, 8, 2],
        [8, 9, 2, 3],
        [1, 7, 0, 1]])

In [47]:
e=torch.randint(size=(3,4),low=0,high=10, dtype=torch.float32) ####random integer

In [48]:
torch.sum(e) ####sum of all elements

tensor(63.)

In [49]:
torch.sum(e,dim=0) ####sum of each column

tensor([20., 16., 12., 15.])

In [50]:
torch.sum(e,dim=1) ###sum of each row

tensor([32., 13., 18.])

In [51]:
torch.mean(e, dim=0) ####mean of each column

tensor([6.6667, 5.3333, 4.0000, 5.0000])

In [52]:
torch.mean(e, dim=1) ####mean of each row

tensor([8.0000, 3.2500, 4.5000])

In [53]:
torch.mean(e) ####mean of all elements

tensor(5.2500)

In [54]:
torch.min(e)

tensor(1.)

In [55]:
torch.max(e)

tensor(9.)

In [56]:
torch.argmax(e) #####it is index of highest value in matrix

tensor(2)

In [58]:
torch.argmin(e) #####it is index of minimum value in matrix

tensor(5)

In [59]:
e

tensor([[8., 7., 9., 8.],
        [5., 1., 2., 5.],
        [7., 8., 1., 2.]])

In [60]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [61]:
f

tensor([[1, 5, 3],
        [4, 0, 2]])

In [62]:
g

tensor([[5, 2],
        [9, 9],
        [1, 3]])

In [63]:
torch.matmul(f,g)######multiplication of matrix

tensor([[53, 56],
        [22, 14]])

In [64]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [65]:
vector1

tensor([1, 2])

In [66]:
vector2

tensor([3, 4])

In [67]:
torch.dot(vector1,vector2)

tensor(11)

In [69]:
f

tensor([[1, 5, 3],
        [4, 0, 2]])

In [70]:
torch.transpose(f, 0,1) ###rows converted to col and col into rows[ 0 dimension means row and 1 col

tensor([[1, 4],
        [5, 0],
        [3, 2]])

In [72]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32) ###square matrix (n*n)

In [73]:
h

tensor([[6., 1., 9.],
        [9., 0., 9.],
        [2., 5., 9.]])

In [74]:
torch.inverse(h)

tensor([[-0.6250,  0.5000,  0.1250],
        [-0.8750,  0.5000,  0.3750],
        [ 0.6250, -0.3889, -0.1250]])

In [75]:
torch.log(h)

tensor([[1.7918, 0.0000, 2.1972],
        [2.1972,   -inf, 2.1972],
        [0.6931, 1.6094, 2.1972]])

In [76]:
torch.exp(h) #######exponential value

tensor([[4.0343e+02, 2.7183e+00, 8.1031e+03],
        [8.1031e+03, 1.0000e+00, 8.1031e+03],
        [7.3891e+00, 1.4841e+02, 8.1031e+03]])

In [78]:
torch.softmax(h,0) ###0 means row wise

tensor([[4.7385e-02, 1.7868e-02, 3.3333e-01],
        [9.5175e-01, 6.5733e-03, 3.3333e-01],
        [8.6788e-04, 9.7556e-01, 3.3333e-01]])

In [79]:
torch.relu(h)

tensor([[6., 1., 9.],
        [9., 0., 9.],
        [2., 5., 9.]])